rabbitmq:
    user: guest
    password: guest
    host: 127.0.0.1
    port: 5672
database:
    user: librenms
    password: librenms
    host: 127.0.0.1
    port: 3306
    database: librenms
poller_modules:
    applications: 1
    aruba-controller: 0
    bgp-peers: 1
    cipsec-tunnels: 0
    cisco-ace-loadbalancer: 0
    cisco-ace-serverfarms: 0
    cisco-asa-firewall: 0
    cisco-cbqos: 0
    cisco-cef: 0
    cisco-ipsec-flow-monitor: 0
    cisco-mac-accounting: 0
    cisco-otv: 0
    cisco-remote-access-monitor: 0
    cisco-sla: 0
    cisco-voice: 0
    cisco-vpdn: 0
    entity-physical: 1
    hr-mib: 1
    ipmi: 1
    ipSystemStats: 1
    junos-atm-vp: 0
    loadbalancers: 0
    mef: 0
    mempools: 1
    mib: 0
    netscaler-vsvr: 0
    netstats: 1
    ntp: 1
    processors: 1
    os: 1
    ospf: 1
    ports: 1
    services: 1
    stp: 1
    toner: 0
    tnms-nbi: 0
    sensors: 1
    storage: 1
    ucd-mib: 1
    ucd-diskio: 1
    unix-agent: 0
    wifi: 0
    wireless: 1
